Sign up
dh-lab/markup-tool pull request #15
Opened 2019-03-21 10:17 UTC by SemBystrov

Без комментариев. Орехус? Орехус.

2019-03-21 13:37 UTC, nikmel2803 requested changes
Надо привести код к единому стилю с помощью `yarn lint` (ну а потом закоммитить и запушить)

2019-03-21 21:41 UTC, ilyamore88 commented
Во время отправки запроса на сервер возникала ошибка, связанная с CORS. В качестве решения прописал заголовки в Backend для разрешения кроссплатформенных запросов.

2019-03-21 21:55 UTC, ilyamore88 commented
Closes #10

2019-03-22 07:24 UTC, nikmel2803 requested changes

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/components/SignUpForm.vue
> +      let data = {
`const`

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/components/SignUpForm.vue
> +      axios.post('http://localhost:3000/sign-up', data)
Лучше использовать async/await

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/components/SignUpForm.vue
> +            alert('Что-то пошло не так!');
`alert` использовать нехорошо, он блокирует поток и раздражает :D 
Лучше просто в консоль пока логгировать, потом сделаем нормальные уведомления

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +         &__dhlogo{
1) Тут не должно быть таба
2) перед  `&__dhlogo{` пустая строка

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +  <div class="signup">
`sign-up` лучше, мне кажется

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/components/SignUpForm.vue
> +      <input required v-model="username" type="text" placeholder="Иванов Иван Иванович"/><br><br>
у нас пока нет `username`. Для логина нужна только почта

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +     <SignUpForm />
По-моему нет смысла выделять форму в отдельный компонент. Либо сделать универсальный компонент для любой формы (для логина например)

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +  <div class="signup">
а ещё лучше `sign-up-page`

2019-03-22 07:24 UTC, nikmel2803 commented on frontend/src/components/SignUpForm.vue
> +<style scoped>
Тут лучше обойтись без `scoped`
https://medium.com/@vjkosmos/использование-bem-в-vue-c6dca5e17f87

2019-03-22 18:28 UTC, nikmel2803 requested changes

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +    <div class="SignUpForm">
sign-up-page__form

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +        <input required v-model="email" id="email" type="email" placeholder="ivanivanov@mail.ru"/><br><br>
вроде id нигде не используется. Если так, лучше их убрать

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +          let response = await axios.post('http://localhost:3000/sign-up', data);
`const`))))

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +    <div class="SignUpForm">
а вообще можно убрать этот класс - он нигде не используется

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +<style scoped>
scoped убрать лучше (уже делал такой коммент)

2019-03-22 18:28 UTC, nikmel2803 commented on frontend/src/views/SignUp.vue
> +    <div class="SignUpForm">
https://ru.bem.info/methodology/quick-start/
можно хотя бы эту страничку почитать, чтобы понять что такое БЭМ

2019-03-22 19:05 UTC, ilyamore88 commented on frontend/src/views/SignUp.vue
> +        <input required v-model="email" id="email" type="email" placeholder="ivanivanov@mail.ru"/><br><br>
Добавил их для label

2019-03-22 19:12 UTC, nikmel2803 approved these changes

2019-03-22 20:39 UTC, daniilpashv10 approved these changes

2019-03-22 20:42 UTC, merged