ModalWindow
dh-lab/markup-tool pull request #18
Opened 2019-03-22 20:56 UTC by daniilpashv10

2019-03-23 18:00 UTC, nikmel2803 requested changes

2019-03-23 18:00 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> -    name: 'Editor'
надо вернуть эту строчку

2019-03-23 18:00 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +      <div class="editor__content"><br>
`<br>` тут не нужен

2019-03-23 18:00 UTC, nikmel2803 commented on frontend/src/components/ModalWindow.vue
> +              <button class="modal-default-button" @click="$emit('close')">
```suggestion
              <button class="modal-window__default-button" @click="$emit('close')">
```

2019-03-23 18:23 UTC, nikmel2803 commented on frontend/src/components/ModalWindow.vue
> +      font-family: Helvetica, Arial, sans-serif;
это тоже не нужно

2019-03-23 19:39 UTC, ilyamore88 approved these changes

2019-03-24 04:40 UTC, nikmel2803 approved these changes

2019-03-24 04:41 UTC, merged