Select words
dh-lab/markup-tool pull request #22
Opened 2019-03-25 04:54 UTC by ilyamore88

Выделение слов по клику

2019-03-28 21:14 UTC, daniilpashv10 approved these changes

2019-03-29 14:54 UTC, nikmel2803 requested changes

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +      <div class="editor__content" v-on:dblclick="selectWord">
```suggestion
      <div class="editor__content" @dblclick="selectWord">
```

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +            range.startContainer.parentElement.outerHTML = range.startContainer.parentElement.outerHTML.replace(/<[^>]*>/g, '');
```suggestion
            range.startContainer.parentElement.outerHTML = range.startContainer.parentElement.innerHTML;
```

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +        if (text.length > 1 || text === ' ') {
Добавь коммент к этому условию плз

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +          if (range.startContainer.parentElement.classList.contains('editor__content-selected')) {
1) добавь коммент к условию
2) Мне кажется, `range.startContainer.parentElement` стоит вынести в отдельную переменную, так как ты часто обращаешься к ней. Так будет проще читать и код чище станет

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +          highlightSpan.className = 'editor__content-selected';
Стоит вынести это в отдельную переменную и описать
типо
```js
/*
 * @const {String} - classname for selected span
 */
const selectedClass = 'editor__content-selected';
```

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +        const text = selection.toString();
если назвать `selectedText`, то код читать проще будет

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +        const range = selection.getRangeAt(0);
аналогично `selectedRange`

2019-03-29 14:54 UTC, nikmel2803 commented on frontend/src/views/Editor.vue
> +          const highlightSpan = document.createElement('span');
возможно, для большей абстракции стоит `'span'` вынести в отдельную переменную, а переменную назвать hightlighElement

2019-03-29 15:49 UTC, nikmel2803 approved these changes

2019-03-30 07:42 UTC, IraKaf approved these changes

2019-03-30 08:15 UTC, merged