Get text by ID
dh-lab/markup-tool pull request #41
Opened 2019-04-02 20:17 UTC by ilyamore88

Closes #38

2019-04-02 20:19 UTC, ilyamore88 commented
Возможно, стоит переименовать файл `text.js` в что-то более понятное. Например, `textById.js`

2019-04-03 06:06 UTC, nikmel2803 commented on backend/routes/texts/text.js
> +router.get('/texts/:textId/markup', async (req, res) => {
тут надо без `/markup`. Это просто API, с помощью которого фронт получит текст. Вот уже на фротке будет `/markup`

2019-04-03 06:06 UTC, nikmel2803 commented on backend/routes/texts/text.js
> +    await Text.findOne({
либо `await` либо `callback`
await предпочтительнее
`const text = await Text.findOne...`

2019-04-03 15:20 UTC, nikmel2803 requested changes
- упростить структуру роутов для API работы с текстами
- добавить новую линию в texts.js (это для души :D)

2019-04-03 18:17 UTC, nikmel2803 approved these changes

2019-04-03 18:29 UTC, daniilpashv10 approved these changes

2019-04-03 19:24 UTC, merged