Sign
dh-lab/markup-tool pull request #53
Opened 2019-04-05 10:56 UTC by SemBystrov

closes #27

2019-04-05 19:57 UTC, nikmel2803 requested changes
+ выпилить модуль user, он сейчас не относится к этому реквесту и неизвестно когда будет использоваться

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +      axios.get('/login?email=' + user.email + '&password=' + user.password)
использование такого синтаксиса параметров нагляднее
```js
axios.get('/user', {
    params: {
      ID: 12345
    }
})
```

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +  [AUTH_REQUEST]: ({ commit, dispatch }, user) => {
переписать на современный синтаксис как в доках: https://vuex.vuejs.org/ru/guide/mutations.html#испоnьзование-констант-дnя-обозначения-типов-мутаций

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +        .then(resp => {
переписать на async/await синтаксис, вместо `.then` и `.catch`

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +  [AUTH_LOGOUT]: ({ commit }) => {
в нашем случае вроде как нет смысла выносить это в отдельный action. Лучше его удалить, а `localStorage.removeItem('user-token')` перенести в соответствующую мутацию

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +          axios.defaults.headers.common['Authorization'] = token;
строчку кода выше и эту лучше занести в мутацию `AUTH_SUCCESS`

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +          localStorage.removeItem('user-token');
аналогично

2019-04-05 19:57 UTC, nikmel2803 commented on frontend/store/modules/auth.js
> +      localStorage.removeItem('user-token');
и туть

2019-04-08 19:50 UTC, nikmel2803 requested changes

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/App.vue
> +    <div id="header">
только БЭМ, только хардкор
`app__header`

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/store/modules/auth.js
> +    axios.defaults.headers.common['Authorization'] = '';
```suggestion
    delete axios.defaults.headers.common['Authorization'];
```

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/views/SignIn.vue
> +  <div class="sign-page">
`auth-page`

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/views/SignIn.vue
> +    <img alt="DH logo" src="../assets/logodh.jpg" class="dhlogo">
auth-page__dh-logo

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/views/SignIn.vue
> +        this.$store.dispatch(AUTH_REQUEST, { email, password }).then(() => {
async/await

2019-04-08 19:50 UTC, nikmel2803 commented on frontend/src/views/SignOut.vue
> +      signout: function () {
signOut

2019-04-10 13:25 UTC, nikmel2803 requested changes

2019-04-10 13:25 UTC, nikmel2803 commented on frontend/src/App.vue
> +    <div id="app__header">
class="

2019-04-10 13:25 UTC, nikmel2803 commented on frontend/src/views/SignOut.vue
> +<style scoped>
```suggestion
<style>
```

2019-04-10 13:36 UTC, nikmel2803 approved these changes
слава богу

2019-04-10 13:38 UTC, SemBystrov commented
Зачем ты называешь меня богом, мы же друзья)))

2019-04-10 13:47 UTC, IraKaf approved these changes

2019-04-10 14:09 UTC, merged